
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Minor Code Smell", "S1075:URIs should not be hardcoded", Justification = "<Pending>", Scope = "member", Target = "~F:Connect.Mobile.Constants.RestUrlDeliveryForm")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Potential Code Quality Issues", "RECS0165:Asynchronous methods should return a Task instead of void", Justification = "<Pending>", Scope = "member", Target = "~M:Connect.Mobile.ViewModel.OperationRangeViewModel.#ctor")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Connect.Mobile.App.Initialize(System.IServiceProvider)")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Connect.Mobile.App.Launch(System.IServiceProvider)")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Connect.Mobile.App.OnStart")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Connect.Mobile.Converters.FloatNullableToStringConverter.ConvertBack(System.Object,System.Type,System.Object,System.Globalization.CultureInfo)~System.Object")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Connect.Mobile.Services.NavigationService.InternalNavigateToAsync(System.Type,System.Object)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Connect.Mobile.View.MainView.#ctor")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Connect.Mobile.ViewModel.DetailHomeViewModel.ExecuteSelectRoomCommand(Connect.Model.Room)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Connect.Mobile.ViewModel.DetailViewModel.ExecuteNotificationsCommand~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Connect.Mobile.ViewModel.DetailViewModel.ValidateCbNotification(System.Object)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Connect.Mobile.ViewModel.MainViewModel.Initialize(System.Object,System.Func{System.Object,System.Threading.Tasks.Task},System.Func{System.Object,System.Threading.Tasks.Task})")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Connect.Mobile.ViewModel.MasterViewModel.ExecuteClickLocationCommand~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Connect.Mobile.ViewModel.MasterViewModel.ExecuteSelectRoomCommand(Connect.Model.Room)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Connect.Mobile.ViewModel.NotificationViewModel.ExecuteCancelCommand~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Connect.Mobile.ViewModel.NotificationViewModel.ExecuteCloseCommand~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Connect.Mobile.ViewModel.NotificationViewModel.ExecuteConfirmCommand~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Connect.Mobile.ViewModel.NotificationViewModel.ExecuteCreateNotificationCommand~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Connect.Mobile.ViewModel.NotificationViewModel.ExecuteDeleteAllNotificationCommand~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Connect.Mobile.ViewModel.NotificationViewModel.ExecuteDeleteNotificationCommand(System.Object)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Connect.Mobile.ViewModel.NotificationViewModel.ExecuteEditNotificationCommand(System.Object)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Connect.Mobile.ViewModel.NotificationViewModel.ExecuteOnOffNotificationCommand(System.Object)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Connect.Mobile.ViewModel.OperationRangeViewModel.ExecuteCancelCommand~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Connect.Mobile.ViewModel.OperationRangeViewModel.ExecuteConfirmCommand~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Connect.Mobile.ViewModel.OperationRangeViewModel.ExecuteDeleteOpRangeCommand~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Connect.Mobile.ViewModel.OperationRangeViewModel.Initialize(System.Object,System.Func{System.Object,System.Threading.Tasks.Task},System.Func{System.Object,System.Threading.Tasks.Task})")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Connect.Mobile.ViewModel.PlugCellViewModel.ExecuteSettingsPlugCommand(Connect.Model.ConnectedObject)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Connect.Mobile.ViewModel.SensorCellViewModel.ExecuteSettingsSensorCommand(Connect.Model.ConnectedObject)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Connect.Mobile.ViewModel.SensorCellViewModel.ValidateCbNotification(System.Object)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Connect.Mobile.ViewModel.SettingsViewModel.AddOperationRangeAsync(System.Object)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Connect.Mobile.ViewModel.SettingsViewModel.ExecuteCloseCommand~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Connect.Mobile.ViewModel.SettingsViewModel.ExecuteCreateOpRangeCommand~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Connect.Mobile.ViewModel.SettingsViewModel.ExecuteDeleteAllOpRangeCommand~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Connect.Mobile.ViewModel.SettingsViewModel.ExecuteEditOpRangeCommand(Connect.Model.OperationRange)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Connect.Mobile.ViewModel.SettingsViewModel.OnDisappearing~System.Threading.Tasks.Task")]
