
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0063:Use simple 'using' statement", Justification = "<Pending>", Scope = "member", Target = "~M:Novacor.Core.Log.Logger.writerApplicationLog(System.Text.StringBuilder)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0063:Use simple 'using' statement", Justification = "<Pending>", Scope = "member", Target = "~M:Novacor.Core.Log.Logger.writerUserLog(System.Text.StringBuilder)")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Framework.Core.Async.NotifyTaskCompletion.WatchTaskAsync(System.Threading.Tasks.Task)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Framework.Core.Async.PeriodicService`1.ExecuteAsync(System.Threading.CancellationToken,System.Func{Framework.Core.Base.Maybe{`0},System.Threading.CancellationToken,System.Threading.Tasks.Task})~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Framework.Core.Async.TaskExtensions.FireAndForgetSafeAsync(System.Threading.Tasks.Task,Framework.Core.Async.IErrorHandler)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Framework.Core.Web.Internet.CheckConnectivity~System.Boolean")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0063:Use simple 'using' statement", Justification = "<Pending>", Scope = "member", Target = "~M:Framework.Core.Services.ErrorHandlerWebService.HandleErrorAsync(System.Net.Http.HttpResponseMessage,System.String,System.Int32)~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0063:Use simple 'using' statement", Justification = "<Pending>", Scope = "member", Target = "~M:Framework.Core.Services.JsonFileService.ReadFile``1~System.Threading.Tasks.Task{``0}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0063:Use simple 'using' statement", Justification = "<Pending>", Scope = "member", Target = "~M:Framework.Core.Services.JsonFileService.WriteFile``1(``0)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0063:Use simple 'using' statement", Justification = "<Pending>", Scope = "member", Target = "~M:Framework.Core.Services.UdpCommunicationService.SendMessage(System.String,System.Int32,System.String)~System.Threading.Tasks.Task{System.Int32}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0063:Use simple 'using' statement", Justification = "<Pending>", Scope = "member", Target = "~M:Framework.Core.Services.UdpCommunicationService.StartReception(System.Int32)~System.Threading.Tasks.Task{System.Byte[]}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0063:Use simple 'using' statement", Justification = "<Pending>", Scope = "member", Target = "~M:Framework.Core.Services.TypedWebService.DeleteAsync``1(System.String,System.String,System.Threading.CancellationToken,System.Int32)~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0063:Use simple 'using' statement", Justification = "<Pending>", Scope = "member", Target = "~M:Framework.Core.Services.TypedWebService.GetAsync``1(System.String,System.String,System.Threading.CancellationToken,System.Int32)~System.Threading.Tasks.Task{``0}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0063:Use simple 'using' statement", Justification = "<Pending>", Scope = "member", Target = "~M:Framework.Core.Services.TypedWebService.GetCollectionAsync``1(System.String,System.String,System.Threading.CancellationToken,System.Int32)~System.Threading.Tasks.Task{System.Collections.Generic.IEnumerable{``0}}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0063:Use simple 'using' statement", Justification = "<Pending>", Scope = "member", Target = "~M:Framework.Core.Services.TypedWebService.HeadAsync``1(System.String,System.String,System.Threading.CancellationToken,System.Int32)~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0063:Use simple 'using' statement", Justification = "<Pending>", Scope = "member", Target = "~M:Framework.Core.Services.TypedWebService.PostAsync``1(System.String,System.String,``0,System.Threading.CancellationToken,System.Int32)~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0063:Use simple 'using' statement", Justification = "<Pending>", Scope = "member", Target = "~M:Framework.Core.Services.TypedWebService.PutAsync``1(System.String,System.String,``0,System.Threading.CancellationToken,System.Int32)~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Framework.Core.Services.AppSettingsService.ReadAllSettings~System.Collections.Specialized.NameValueCollection")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Framework.Core.Services.AppSettingsService.ReadSetting(System.String)~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Framework.Core.Services.SignalRService.ConnectToServerAsync~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Framework.Core.Services.SignalRService.Receive")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Framework.Core.Services.TypedWebService.QueryCurrencyServiceWithRetryPolicy(System.Func{System.Threading.Tasks.Task{System.Net.Http.HttpResponseMessage}})~System.Threading.Tasks.Task{System.Net.Http.HttpResponseMessage}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification = "<Pending>", Scope = "member", Target = "~M:Framework.Core.Services.ErrorHandlerWebService.HandleErrorAsync(System.Net.Http.HttpResponseMessage,System.String,System.Int32)~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Code Quality", "IDE0052:Remove unread private members", Justification = "<Pending>", Scope = "member", Target = "~P:Framework.Core.Services.MockAuthenticationService.ClientId")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Code Quality", "IDE0052:Remove unread private members", Justification = "<Pending>", Scope = "member", Target = "~P:Framework.Core.Services.MockAuthenticationService.ClientSecret")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Code Quality", "IDE0052:Remove unread private members", Justification = "<Pending>", Scope = "member", Target = "~P:Framework.Core.Services.MockAuthenticationService.Scope")]