//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Connect.Mobile.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Connect.Mobile.Resources.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }

        internal static string EditNotification
        {
            get
            {
                return ResourceManager.GetString("EditNotification", resourceCulture);
            }
        }

        internal static string AddNotification
        {
            get
            {
                return ResourceManager.GetString("AddNotification", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adjuvant.
        /// </summary>
        internal static string Adjuvant {
            get {
                return ResourceManager.GetString("Adjuvant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Affair.
        /// </summary>
        internal static string Affair {
            get {
                return ResourceManager.GetString("Affair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Affair Id.
        /// </summary>
        internal static string AffairId {
            get {
                return ResourceManager.GetString("AffairId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Broken down amount.
        /// </summary>
        internal static string AlreadyBreakdowned {
            get {
                return ResourceManager.GetString("AlreadyBreakdowned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Broken down amount.
        /// </summary>
        internal static string AlreadyBreakdownedCsv {
            get {
                return ResourceManager.GetString("AlreadyBreakdownedCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à It has already been scanned..
        /// </summary>
        internal static string AlreadyScanned {
            get {
                return ResourceManager.GetString("AlreadyScanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ScanSite.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à at the date.
        /// </summary>
        internal static string AtDate {
            get {
                return ResourceManager.GetString("AtDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unable to add the delivery form. It already exists..
        /// </summary>
        internal static string BONBETON_ALREADY_EXIST {
            get {
                return ResourceManager.GetString("BONBETON_ALREADY_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The broken down amount for the delivery form is greater than the delivered amount..
        /// </summary>
        internal static string BONBETON_BREAKDOWN_NO_REMAINING_QUANTITY {
            get {
                return ResourceManager.GetString("BONBETON_BREAKDOWN_NO_REMAINING_QUANTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The breakdown corresponding is unknown.
        /// </summary>
        internal static string BONBETON_BREAKDOWN_NOTFOUND {
            get {
                return ResourceManager.GetString("BONBETON_BREAKDOWN_NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unable to load the delivery form.
        /// </summary>
        internal static string BONBETON_NOTFOUND {
            get {
                return ResourceManager.GetString("BONBETON_NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This position is already broken down..
        /// </summary>
        internal static string BONBETON_VENTILATION_POSITON_ALREADY_EXIST {
            get {
                return ResourceManager.GetString("BONBETON_VENTILATION_POSITON_ALREADY_EXIST", resourceCulture);
            }
        }

        internal static string ErrorOperationRange
        {
            get
            {
                return ResourceManager.GetString("ErrorOperationRange", resourceCulture);
            }
        }

        internal static string ErrorAuthentication
        {
            get
            {
                return ResourceManager.GetString("ErrorAuthentication", resourceCulture);
            }
        }

        internal static string ErrorNotification
        {
            get
            {
                return ResourceManager.GetString("ErrorNotification", resourceCulture);
            }
        }

        internal static string OverlapingRange
        {
            get
            {
                return ResourceManager.GetString("OverlapingRange", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Breakdown.
        /// </summary>
        internal static string Breakdown {
            get {
                return ResourceManager.GetString("Breakdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Breakdowns list.
        /// </summary>
        internal static string BreakdownList {
            get {
                return ResourceManager.GetString("BreakdownList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Building.
        /// </summary>
        internal static string Building {
            get {
                return ResourceManager.GetString("Building", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Building code.
        /// </summary>
        internal static string BuildingCode {
            get {
                return ResourceManager.GetString("BuildingCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Building.
        /// </summary>
        internal static string BuildingCsv {
            get {
                return ResourceManager.GetString("BuildingCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Central.
        /// </summary>
        internal static string Central {
            get {
                return ResourceManager.GetString("Central", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Certification.
        /// </summary>
        internal static string Certification {
            get {
                return ResourceManager.GetString("Certification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chlorure class.
        /// </summary>
        internal static string ChlorureClass {
            get {
                return ResourceManager.GetString("ChlorureClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Concrete.
        /// </summary>
        internal static string Concrete {
            get {
                return ResourceManager.GetString("Concrete", resourceCulture);
            }
        }

        internal static string Warning
        {
            get
            {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }

        internal static string NoElement
        {
            get
            {
                return ResourceManager.GetString("NoElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type of concrete.
        /// </summary>
        internal static string ConcreteType {
            get {
                return ResourceManager.GetString("ConcreteType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you confirm to delete the element .
        /// </summary>
        internal static string ConfirmRemove {
            get {
                return ResourceManager.GetString("ConfirmRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Synchronization conflict.
        /// </summary>
        internal static string ConflictSynchro {
            get {
                return ResourceManager.GetString("ConflictSynchro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connection.
        /// </summary>
        internal static string Connection {
            get {
                return ResourceManager.GetString("Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Consistency.
        /// </summary>
        internal static string Consistency {
            get {
                return ResourceManager.GetString("Consistency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Creation date.
        /// </summary>
        internal static string CreationDate {
            get {
                return ResourceManager.GetString("CreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Creation date.
        /// </summary>
        internal static string CreationDateCsv {
            get {
                return ResourceManager.GetString("CreationDateCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Customer.
        /// </summary>
        internal static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }

        internal static string Delete
        {
            get
            {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Removal date.
        /// </summary>
        internal static string DeleteDate {
            get {
                return ResourceManager.GetString("DeleteDate", resourceCulture);
            }
        }

        internal static string DeleteOperationRange
        {
            get
            {
                return ResourceManager.GetString("DeleteOperationRange", resourceCulture);
            }
        }

        internal static string DeleteOperationRanges
        {
            get
            {
                return ResourceManager.GetString("DeleteOperationRanges", resourceCulture);
            }
        }

        internal static string DeleteNotifications
        {
            get
            {
                return ResourceManager.GetString("DeleteNotifications", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delivered amount.
        /// </summary>
        internal static string DeliveredQty {
            get {
                return ResourceManager.GetString("DeliveredQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delivery date.
        /// </summary>
        internal static string DeliveryDate {
            get {
                return ResourceManager.GetString("DeliveryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delivery form.
        /// </summary>
        internal static string DeliveryForm {
            get {
                return ResourceManager.GetString("DeliveryForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à delivery form.
        /// </summary>
        internal static string DeliveryFormLC {
            get {
                return ResourceManager.GetString("DeliveryFormLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Forms list.
        /// </summary>
        internal static string DeliveryFormList {
            get {
                return ResourceManager.GetString("DeliveryFormList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delivery forms list.
        /// </summary>
        internal static string DeliveryFormListButton {
            get {
                return ResourceManager.GetString("DeliveryFormListButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Designation.
        /// </summary>
        internal static string Designation {
            get {
                return ResourceManager.GetString("Designation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Designation.
        /// </summary>
        internal static string DesignationCsv {
            get {
                return ResourceManager.GetString("DesignationCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dosage.
        /// </summary>
        internal static string Dosage {
            get {
                return ResourceManager.GetString("Dosage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Effectiveness binder.
        /// </summary>
        internal static string EffectivenessBinder {
            get {
                return ResourceManager.GetString("EffectivenessBinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Non-synchronized element.
        /// </summary>
        internal static string ElementNotSynchronized {
            get {
                return ResourceManager.GetString("ElementNotSynchronized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à EndDate.
        /// </summary>
        internal static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The broken down quantity is inconsistent with the value of the server..
        /// </summary>
        internal static string ErroprDispatchInconsistency {
            get {
                return ResourceManager.GetString("ErroprDispatchInconsistency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unable to add or edit the breakdown.
        /// </summary>
        internal static string ErrorAddEditDispatch {
            get {
                return ResourceManager.GetString("ErrorAddEditDispatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unable to add the delivery form.
        /// </summary>
        internal static string ErrorAddingDeliveryForm {
            get {
                return ResourceManager.GetString("ErrorAddingDeliveryForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unable to complete the task.
        /// </summary>
        internal static string ErrorCompleteTask {
            get {
                return ResourceManager.GetString("ErrorCompleteTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The data matric format is not correct..
        /// </summary>
        internal static string ErrorDataMatrixFormat {
            get {
                return ResourceManager.GetString("ErrorDataMatrixFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The amount must be an integer value..
        /// </summary>
        internal static string ErrorDecimalValue {
            get {
                return ResourceManager.GetString("ErrorDecimalValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unable to delete the delivery form.
        /// </summary>
        internal static string ErrorDeletingDeliveryForm {
            get {
                return ResourceManager.GetString("ErrorDeletingDeliveryForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Incorrect breakdown.
        /// </summary>
        internal static string ErrorDispatch {
            get {
                return ResourceManager.GetString("ErrorDispatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You must select a position..
        /// </summary>
        internal static string ErrorEmptyPosition {
            get {
                return ResourceManager.GetString("ErrorEmptyPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unable to export the delivery forms.
        /// </summary>
        internal static string ErrorExportingDeliveryForm {
            get {
                return ResourceManager.GetString("ErrorExportingDeliveryForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The amount is not valid..
        /// </summary>
        internal static string ErrorIncorrectValue {
            get {
                return ResourceManager.GetString("ErrorIncorrectValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unable to launch the scan.
        /// </summary>
        internal static string ErrorLaunchingScan {
            get {
                return ResourceManager.GetString("ErrorLaunchingScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unable to load the delivery forms.
        /// </summary>
        internal static string ErrorLoadingDeliveryForm {
            get {
                return ResourceManager.GetString("ErrorLoadingDeliveryForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unable to load the breakdowns.
        /// </summary>
        internal static string ErrorLoadingDispatch {
            get {
                return ResourceManager.GetString("ErrorLoadingDispatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unable to load the projects.
        /// </summary>
        internal static string ErrorLoadingProject {
            get {
                return ResourceManager.GetString("ErrorLoadingProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unable to send the email.
        /// </summary>
        internal static string ErrorMail {
            get {
                return ResourceManager.GetString("ErrorMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The remaining amount can not be negative..
        /// </summary>
        internal static string ErrorNegativeValue {
            get {
                return ResourceManager.GetString("ErrorNegativeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The position is inconsistent with the value of the server..
        /// </summary>
        internal static string ErrorPositionInconsistency {
            get {
                return ResourceManager.GetString("ErrorPositionInconsistency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unable to save the project.
        /// </summary>
        internal static string ErrorSavingProject {
            get {
                return ResourceManager.GetString("ErrorSavingProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unable to select the delivery form.
        /// </summary>
        internal static string ErrorSelectingDeliveryForm {
            get {
                return ResourceManager.GetString("ErrorSelectingDeliveryForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The server doesn&apos;t answer.
        /// </summary>
        internal static string ErrorServer {
            get {
                return ResourceManager.GetString("ErrorServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unable to synchronize the delivery forms.
        /// </summary>
        internal static string ErrorSynchronizingDeliveryForm {
            get {
                return ResourceManager.GetString("ErrorSynchronizingDeliveryForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The amount can not be zero..
        /// </summary>
        internal static string ErrorZeroValue {
            get {
                return ResourceManager.GetString("ErrorZeroValue", resourceCulture);
            }
        }

        internal static string DayCannotBeNull
        {
            get
            {
                return ResourceManager.GetString("DayCannotBeNull", resourceCulture);
            }
        }

        internal static string TimeCannotBeNull
        {
            get
            {
                return ResourceManager.GetString("TimeCannotBeNull", resourceCulture);
            }
        }

        internal static string StartEndTime
        {
            get
            {
                return ResourceManager.GetString("StartEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export Csv of the project.
        /// </summary>
        internal static string ExportCsvProject {
            get {
                return ResourceManager.GetString("ExportCsvProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exposure class.
        /// </summary>
        internal static string ExposureClass {
            get {
                return ResourceManager.GetString("ExposureClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Formula.
        /// </summary>
        internal static string Formula {
            get {
                return ResourceManager.GetString("Formula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Granularity.
        /// </summary>
        internal static string Granularity {
            get {
                return ResourceManager.GetString("Granularity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Granularity.
        /// </summary>
        internal static string GranularityCsv {
            get {
                return ResourceManager.GetString("GranularityCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Humidity.
        /// </summary>
        internal static string Humidity {
            get {
                return ResourceManager.GetString("Humidity", resourceCulture);
            }
        }

        internal static string Pressure
        {
            get
            {
                return ResourceManager.GetString("Pressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Deleted.
        /// </summary>
        internal static string IsDeleted {
            get {
                return ResourceManager.GetString("IsDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you want to keep the local value ?.
        /// </summary>
        internal static string KeepValue {
            get {
                return ResourceManager.GetString("KeepValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Level.
        /// </summary>
        internal static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Local.
        /// </summary>
        internal static string Local {
            get {
                return ResourceManager.GetString("Local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Logout.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Menu.
        /// </summary>
        internal static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Not connected.
        /// </summary>
        internal static string NotConnected {
            get {
                return ResourceManager.GetString("NotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Not synchronized.
        /// </summary>
        internal static string NotSynchronized {
            get {
                return ResourceManager.GetString("NotSynchronized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Not synchronized and not added.
        /// </summary>
        internal static string NotSynchronizedNotAdded {
            get {
                return ResourceManager.GetString("NotSynchronizedNotAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Number.
        /// </summary>
        internal static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Number.
        /// </summary>
        internal static string NumberCsv {
            get {
                return ResourceManager.GetString("NumberCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Off.
        /// </summary>
        internal static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à On.
        /// </summary>
        internal static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Would you like to program your connected object.
        /// </summary>
        internal static string OpenProgramming {
            get {
                return ResourceManager.GetString("OpenProgramming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Position.
        /// </summary>
        internal static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Programming.
        /// </summary>
        internal static string Programming {
            get {
                return ResourceManager.GetString("Programming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unable to find the project.
        /// </summary>
        internal static string PROJECT_NOT_FOUND {
            get {
                return ResourceManager.GetString("PROJECT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Amount.
        /// </summary>
        internal static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Amount.
        /// </summary>
        internal static string QuantityCsv {
            get {
                return ResourceManager.GetString("QuantityCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extra charge.
        /// </summary>
        internal static string QuantitySupplement {
            get {
                return ResourceManager.GetString("QuantitySupplement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extra charge.
        /// </summary>
        internal static string QuantitySupplementCsv {
            get {
                return ResourceManager.GetString("QuantitySupplementCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Question.
        /// </summary>
        internal static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remaining to break down.
        /// </summary>
        internal static string RemainingQty {
            get {
                return ResourceManager.GetString("RemainingQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Resilience.
        /// </summary>
        internal static string Resilience {
            get {
                return ResourceManager.GetString("Resilience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Resilience.
        /// </summary>
        internal static string ResilienceCsv {
            get {
                return ResourceManager.GetString("ResilienceCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select a building.
        /// </summary>
        internal static string SelectBuilding {
            get {
                return ResourceManager.GetString("SelectBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select a level.
        /// </summary>
        internal static string SelectLevel {
            get {
                return ResourceManager.GetString("SelectLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select a position.
        /// </summary>
        internal static string SelectPosition {
            get {
                return ResourceManager.GetString("SelectPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Server.
        /// </summary>
        internal static string Server {
            get {
                return ResourceManager.GetString("Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à StartDate.
        /// </summary>
        internal static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select the data matrix to start to scan a .
        /// </summary>
        internal static string StartScan {
            get {
                return ResourceManager.GetString("StartScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supplement.
        /// </summary>
        internal static string Supplement {
            get {
                return ResourceManager.GetString("Supplement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supplement.
        /// </summary>
        internal static string SupplementCsv {
            get {
                return ResourceManager.GetString("SupplementCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Synchronized.
        /// </summary>
        internal static string Synchronized {
            get {
                return ResourceManager.GetString("Synchronized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Temperature.
        /// </summary>
        internal static string Temperature {
            get {
                return ResourceManager.GetString("Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Torch.
        /// </summary>
        internal static string Torch {
            get {
                return ResourceManager.GetString("Torch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Last update date.
        /// </summary>
        internal static string UpdateDate {
            get {
                return ResourceManager.GetString("UpdateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User Id.
        /// </summary>
        internal static string UserId {
            get {
                return ResourceManager.GetString("UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à OK.
        /// </summary>
        internal static string Validate {
            get {
                return ResourceManager.GetString("Validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Version.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delivered volume.
        /// </summary>
        internal static string VolumeDelivered {
            get {
                return ResourceManager.GetString("VolumeDelivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delivered volume.
        /// </summary>
        internal static string VolumeDeliveredCsv {
            get {
                return ResourceManager.GetString("VolumeDeliveredCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ordered volume.
        /// </summary>
        internal static string VolumeOrdered {
            get {
                return ResourceManager.GetString("VolumeOrdered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ordered volume.
        /// </summary>
        internal static string VolumeOrderedCsv {
            get {
                return ResourceManager.GetString("VolumeOrderedCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Waiting.
        /// </summary>
        internal static string Waiting {
            get {
                return ResourceManager.GetString("Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Incorrect username or password.
        /// </summary>
        internal static string WRONG_LOGIN_OR_PASSWORD {
            get {
                return ResourceManager.GetString("WRONG_LOGIN_OR_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
