name: AirZapto-WebServer.yml

on:
  workflow_dispatch:
  push:
    branches: [ main ]

env:
  DOTNET_VERSION: "8.x"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          
      - name : Restore
        run: dotnet restore ./AirZapto.WebServer.sln

      - name : Build
        run : dotnet build ./AirZapto.WebServer.sln --configuration release --no-restore

      - name : Test
        run : dotnet test ./AirZapto.WebServer.sln --configuration release --no-restore --no-build
  
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./AirZapto.WebServer/Dockerfile
          push: true
          tags: mickabdocker/airzaptowebserver:v2
    
