
name: AirZapto-WebServer-Build.yml

on:
  workflow_dispatch:
  push:
    branches: 
      - main
      - AirZaptoWebServer

env:
  DOTNET_VERSION : "8.x"

jobs:
  build:
    runs-on : ubuntu-latest

    steps:
      - name : Checkout
        uses : actions/checkout@v4
  
      - name : Setup .NET
        uses : actions/setup-dotnet@v3
        with :
          dotnet-version: ${{ env.DOTNET_VERSION }}
          
      - name : Restore
        run : dotnet restore ./AirZapto.WebServer.sln

      - name : Build
        run : dotnet build ./AirZapto.WebServer.sln --configuration release --no-restore

      - name : Test
        run : dotnet test ./AirZapto.WebServer.sln --configuration release --no-restore --no-build
    
