name: Connect.WebServer.build.yml

on:
  workflow_dispatch:
  push:
    branches: [ main ]

env:
  DOTNET_VERSION: "8.x"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
  
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          
      - name : Restore
        run: dotnet restore ./Connect.WebServer.sln

      - name : Build
        run : dotnet build ./Connect.WebServer.sln --configuration release --no-restore

      - name : Test
        run : dotnet test ./Connect.WebServer.sln --configuration release --no-restore --no-build
    
